menus:
  test-menu:
    title: "<yellow>Example menu"
    rows: 4
    items:
      test-item:
        display-name: "<aqua>Test item btw"
        lore:
          - "<red>Test lore btw"
        slot: 10
        material: OAK_LOG
        actions:
          - "[console] kick <player>"
        # action: "[console] mute <player>"

  paginated-menu:
    title: "<gradient:gold:red>hhqhahahah lol (Стор. %page%)"
    size: 54
    items:
      test:
        material: DIAMOND_BLOCK
        display-name: "<aqua>TEST item!!"
        slot: 0
        lore:
          - "<gray>that's will be good"
        actions:
          - "[sound] ENTITY_PLAYER_LEVELUP"
          - "[close-menu]"
      wood:
        material: OAK_LOG
        slot: 1
        display-name: "<aqua>MAYBE LOG MAYBE WOOD"
        lore:
          - "<red>!<gray>that's will be good"
        actions:
          - "[sound] VILLAGER_NO"
          - "[close-menu]"
      woo2d:
        material: OAK_LOG
        slot: 2
        display-name: "<aqua>MAYBE LOG MAYBE WOOD"
        lore:
          - "<red>!<gray>that's will be good"
        actions:
          - "[sound] VILLAGER_NO"
          - "[close-menu]"
      wo33od:
        material: OAK_LOG
        slot: 3
        display-name: "<aqua>MAYBE LOG MAYBE WOOD"
        lore:
          - "<red>!<gray>that's will be good"
        actions:
          - "[sound] VILLAGER_NO"
          - "[close-menu]"